export const WATCH_ALONG_EVENTS = {
  PLAYBACK_PLAY: 'playback.play',
  PLAYBACK_PAUSE: 'playback.pause',
  PLAYBACK_SEEK: 'playback.seek',
  PLAYBACK_SYNC: 'playback.sync',
  PLAYBACK_STATE_CHANGED: 'playback.state.changed',
  CHANGE_EPISODE: 'playback.change_episode',
  SOURCE_CHANGED: 'playback.source.changed',
  ROOM_SNAPSHOT: 'room.snapshot',
  PRESENCE_JOINED: 'presence.joined',
  PRESENCE_LEFT: 'presence.left',
  PRESENCE_KICKED: 'presence.kicked',
  ROOM_KICK: 'room.kick',
  ROOM_JOIN: 'room.join',
  ROOM_LEAVE: 'room.leave',
  ROOM_CLOSED: 'room.closed',
};
